.PHONY: run clean

# Ejecuta programa1.py y luego programa2.py (siempre en este orden)
run:
	python3 LadosLotev4.py    # Genera imagen.png (siempre)
	python3 TecnicaHoughv2.py    # Procesa la imagen (siempre)

# Limpia los archivos generados
clean:
	rm -f imagen.png 
